version: '3'
services:
    # credentials guest:guest
    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            - '15672:15672'
            - '5672:5672'
    ibmmq:
        image: ibmcom/mq
        ports:
            - '1414:1414'
            - '9443:9443'
            - '9157:9157'
        volumes:
            - qm1data:/mnt/mqm
        stdin_open: true
        tty: true
        restart: always
        environment:
            LICENSE: accept
            MQ_QMGR_NAME: QM1
            MQ_APP_PASSWORD: admin
            MQ_ENABLE_METRICS: "true"
    kconnect:
        image: ibmcase/kconnect:1.0.0
        ports:
            - '8083:8083'
    inventoryapp:
        build: ../inventory-app
        image: ibmcase/eda-inventory-app:1.0.0
        ports:
            - '8082:8080'
    storeSaleGenerator:
        hostname: storeapp
        image: ibmcase/store-sale-producer:1.0.0
        ports:
            - '8080:8080'
        environment:
            AMQP_HOST: rabbitmq
        depends_on:
            - rabbitmq
    itemaggregator:
        hostname: itemaggregator
        image: ibmcase/itemaggregator:1.0.0
        ports:
            - '8081:8080'
    mqlistener:
        hostname: mqlistener
        image: ibmcase/mq-listener:1.0.0
        ports:
            - '8084:8080'
        depends_on:
            - ibmmq
volumes:
    qm1data:
networks:
    default:
        external:
            name: labnet