version: '3'
services:
    kconnect:
        build: ../kconnect
        image: ibmcase/kconlab:1.0.0
        ports:
            - '8083:8083'
    ibmmq:
        image: ibmcom/mq
        ports:
            - '1414:1414'
            - '9443:9443'
            - '9157:9157'
        volumes:
            - qm1data:/mnt/mqm
        stdin_open: true
        tty: true
        restart: always
        environment:
            LICENSE: accept
            MQ_QMGR_NAME: QM1
            MQ_APP_PASSWORD: passw0rd
            MQ_ENABLE_METRICS: "true"
volumes:
    qm1data:
networks:
    default:
        external:
            name: labnet